import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import React, { lazy, Suspense } from "react";
import dynamic from "next/dynamic";
import Head from "next/head";
import TestType from '@mf/next2/test'

// @ts-expect-error app2/Button is a federated module.
const Test = dynamic(() => import('next2/test'), { ssr: false }) as unknown as typeof TestType;


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Suspense>
          <Test>
            <p>これはモジュールをインポートしていますuuuuuuuuuu</p>
          </Test>
        </Suspense>
      </main>
    </>
  );
}
